# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ml-dl-infrastructure',
                'doc_host': 'https://najmehtaleb.github.io',
                'git_url': 'https://github.com/najmehtaleb/ml-dl-infrastructure',
                'lib_path': 'ml_dl_infrastructure'},
  'syms': {'ml_dl_infrastructure.core': {'ml_dl_infrastructure.core.foo': ('core.html#foo', 'ml_dl_infrastructure/core.py')}}}