project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  
  navbar:
    search: true
    title: Machine Learning and Deep Learning Infrastructure
    
    left:
      - text: Home
        href: https://najmehtaleb.github.io/my-site/
        
    right:
      - icon: github
        href: https://github.com/najmehtaleb/ml-dl-infrastructure
      - icon: twitter
        href: https://twitter.com/NajmehTaleb
    
    
  sidebar:
    style: floating
    collapse-level: 1
    contents: auto

metadata-files: [nbdev.yml]